Atom\Uploader\Model\Embeddable\FileReference:
  fs_prefix: embeddableFs
  fs_adapter: flysystem
  uri_prefix: /flysystem-uploads/%s
  naming_strategy: basename
ExampleApp\Entity\ORM\UploadableEntity:
  uri_setter: uriField
  file_info_setter: fileInfoField
  file_setter: fileField
  file_getter: fileField