language: php
sudo: false

php:
  - 5.6
  - 7.0

cache:
  directories:
    - "$HOME/.composer/cache"

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar config --global github-oauth.github.com $GH_TOKEN
  - php -d memory_limit=-1 composer.phar install --no-interaction

script:
  - php composer.phar test

notifications:
  slack:
    secure: UNSWxz7IXcr/TWUuMwLcsZuvilxn1l8MF8TMFXcw3KWCLkfLg1H5IYd0/f2dUJ0ZieF7NdVQ5wOIBLE0LkLgRzumBAoYnOGoDWSYPC89Q1kqz4l6zHeStyU0/Vik/5l96LJWMxBQKA74vI3HXAzzJ2NtZdl9pC2ozWRs10Ltb/xZdNNWhPCyzs6kV3Y877kAXuXOHdTBFXrMGK3drX/PWRFXYidJf5+SKvi55RCQm69k6kWGmlNmf6qCDvTFX0+Jwj3DkxcC6el8lC33GOygyVJMyDN54IX6T0zHerb7mmlDrfeyVh9YcFJZ+u/CRhi7ZEAx5kOxNUlBXYklUHWPS43v0q6NNdM1hON2HjB487sXjJgMAzpVqmRu3XvMSF9qW2nYq/6uarmXM4FMHafEHNFdksHmaQ/MsZSGBuKTs1e0fXAHlUnEZxk17F5uGiorFwv6ZRvnTHBD08wceUktUN1xtf+nPAO03sPM7O+/4cMRCjraxtMmIaGcYcWb1I0ZvWN8XHuJwUftZePhAWez5WJUE6ti353lZywWyyg0YbR4GOx6dzwyRxHW5wTlmslHtAhz5qoLDZ0ZWKppf+wuIUWswG81Dpd1+qTmuJIpXMDvj9U0StDFUBFwC5IH4OC+cISkatCf36XbQN3D93xofp9DgqTCr495iwpJ/6iqqgE=
