language: php
sudo: false
php:
  - 5.6
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction --dev

script:
  - vendor/bin/phpspec -c=phpspec-ci.yml run
  - vendor/bin/behat

after_script:
  - travis_retry vendor/bin/coveralls

notifications:
  webhooks: https://webhooks.gitter.im/e/a083ae222d5812ae9f01