---
- hosts: all
  become: True
  roles:
    - {role: tersmitten.locales, tags: [locales]}
    - {role: cold147.php, tags: [php]}
    - {role: cold147.shell, tags: [shell, zsh, tmux]}
    - {role: jdauphant.nginx, tags: [nginx]}
    - {role: kosssi.composer, tags: [composer]}
  pre_tasks:
    - include: "{{playbook_dir}}/tasks/prepare_app_requirements.yml"

  vars_files:
    - ["{{playbook_dir}}/../secret.yml", "{{playbook_dir}}/../parameters.yml.dist"]

- hosts: vagrant
  pre_tasks:
    - include: "{{ playbook_dir }}/tasks/prepare_dev.yml"